apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
apply plugin: 'kotlin-android'

android {
    namespace 'io.agora.beautyapi.faceunity'
    compileSdk 35

    defaultConfig {
        minSdkVersion 21
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    if (new File("$AGORA_RTC_SDK").exists()) {
        api fileTree(dir: "${AGORA_RTC_SDK}", include: ['*.jar', '*.aar'])
    } else {
        api "$AGORA_RTC_SDK"
    }


    api 'com.faceunity:core:8.14.0'
    api 'com.faceunity:model:8.14.0'
}