# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
#source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
 platform :ios, '11.0'

#plugin 'cocoapods-pod-sign'
#skip_pod_bundle_sign # Used to skip Xcode's signature to bundle resources

target 'BeautyAPi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

#  pod 'AgoraRtcEngine_iOS', '4.2.6'
  pod 'AgoraRtcEngine_Special_iOS', '4.2.6.5'
#  pod 'sdk', :path => 'sdk.podspec'
#  pod 'BeautyAPI', :path => Dir.pwd() + '/BeautyAPi/BeautyAPI.podspec'
  pod 'SenseLib', :path => 'sense.podspec'
  pod 'fuLib', :path => 'fu.podspec'
  pod 'bytedEffect', :path => 'bytedEffect.podspec'
  # pod 'CosmosEffect', :path => './CosmosEffect'
  
  pod 'JXCategoryView', '~> 1.6.1'

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
